#!/usr/bin/env bash
#!/bin/bash

_GLOBAL_EXEC=d_
_LIB=/var/lib/ductn

[[ $# -eq 0 ]] &&
    echo "No arguments supplied" &&
    exit 1

source $_LIB/sys.sh
source $_LIB/php.m2.sh
source $_LIB/php.lar.sh
source $_LIB/git.sh
source $_LIB/log.sh

d_commands() {
    # echo "--commands"
    # declare -F | awk '{print $3}' | cut -f3 -d':' | grep -v -e "^$" | awk '{print " - " $1}'
    # declare -F | awk '{print $3}' | grep -e "^--"
    # declare -F | awk '{print $3}' | grep -e "^--" | awk '{print substr($1, 3, length($1))}'
    declare -F | awk '{print $3}' | grep -e "^$_GLOBAL_EXEC" | sed "s/$_GLOBAL_EXEC//g" | grep -v "commands"
}

[[ (! -x "$_GLOBAL_EXEC$1") && (! $(type -t "$_GLOBAL_EXEC$1") == function) ]] && echo "'$1' is not a ductn command." && exit 1

"$_GLOBAL_EXEC$@"
